Warm-up 실습 1주차
teamcors/EZPZ-Infra-Study pull request #2
Opened 2023-09-06 12:15 UTC by Queue-ri

2023-09-06 14:27 UTC, chaeeun-Han commented
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/blob/eb8d606a8669157c431215729338bfdf0bc934d0/dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java#L41
System.out.println -> log.info로 변경해서 성능 향상시킬 수 있습니다!
ref) https://hudi.blog/do-not-use-system-out-println-for-logging/

2023-09-06 14:43 UTC, nusuy commented
@Queue-ri 
1. for문 안에서 여러 번 `save`를 호출하는 것보다, for문 안에서는 item의 값만 변경하고 마지막에 `saveAll(items)`을 한 번만 호출하는 것이 성능에 더 좋습니다!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/blob/eb8d606a8669157c431215729338bfdf0bc934d0/dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java#L56-L61

2. 개인적인 의견으로, 폴더링을 하는 것이 더 깔끔한 것 같아요!

3. Global 설정으로 서버 timezone 설정하는 부분이 좋았어요!

---

@chaeeun-Han 
1. `@RestController` 어노테이션 안에 `@Component`가 이미 속해있기 때문에 둘을 함께 쓰지 않아야 해요!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/blob/eb8d606a8669157c431215729338bfdf0bc934d0/dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/controller/ApiController.java#L12-L13

2. Entity 이름은 `NaverNewsItem`이고 리포지토리 이름은 `NewsInfoRepository`인데, 리포지토리 이름은 '`엔티티명+Repository`'으로 작성하는 게 좋을 것 같아요! (컨벤션인지까지는 잘 모르겠음)

3. URI를 builder로 생성한 부분이 좋았어요!

4. for문 안에서 매번 `save` 호출하지 않고, `saveAll` 사용하기! (규리언니 1번과 같은 상황 같아요.)
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/blob/eb8d606a8669157c431215729338bfdf0bc934d0/dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/service/RestTemplateService.java#L69-L84

2023-09-15 04:28 UTC, Queue-ri commented on dev/nusuy/ext-search-batch/src/main/java/com/cubix/extsearchbatch/service/DataUpdateService.java
> +        }
`try-catch`를 사용한 점은 매우 훌륭합니다.
다만 현재의 코드로는 뉴스 데이터를 가져오려고 네이버 API를 호출할 때, 네이버쪽에 장애가 발생했을 때의 오류를 구분해서 catch 하는 부분이 없는 것 같습니다.

차후 API로 연결이 되면 동일한 500으로 보내지기 때문에 분리해서 핸들링하는 법을 연습해보면 좋을 것 같아요~

2023-09-15 04:29 UTC, nusuy requested changes

2023-09-15 04:29 UTC, nusuy commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +                "https://openapi.naver.com/v1/search/news.json?query=%EC%A3%BC%EC%8B%9D&display=10&start=1&sort=sim",
`UriComponentsBuilder` 사용해서 URI 생성합시다!

2023-09-15 04:29 UTC, nusuy commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +        newsRepo.save(oldItem);
for문 안에서 여러 번 `save`를 호출하는 것보다, for문 안에서는 item의 값만 변경하고 마지막에 `saveAll(items)`을 한 번만 호출하는 것이 성능에 더 좋습니다!

2023-09-15 04:29 UTC, nusuy commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +        System.out.println("뉴스 데이터 적재 완료");
성능을 위해 `println` 대신 `@Slf4j`의 `log`를 사용합시다!

2023-09-15 04:29 UTC, nusuy commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +    private void checkUpdate(NaverNewsItem newItem, NaverNewsItem oldItem) {
DB에 접근하는 코드가 포함된 메소드에는 트랜잭션이 안전하게 수행될 수 있도록 `@Transactional`을 붙여줍시다!

2023-09-15 04:29 UTC, nusuy commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/service/RestTemplateService.java
> +                newsRepo.save(DBdata);
for문 안에서 여러 번 save를 호출하는 것보다, for문 안에서는 item의 값만 변경하고 마지막에 saveAll(items)을 한 번만 호출하는 것이 성능에 더 좋습니다!

2023-09-15 04:29 UTC, nusuy commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/service/RestTemplateService.java
> +    public String naverApiTest() throws CharacterCodingException {
DB에 접근하는 코드가 포함된 메소드에는 트랜잭션이 안전하게 수행될 수 있도록 `@Transactional`을 붙여줍시다!

2023-09-15 04:51 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +    private void checkUpdate(NaverNewsItem newItem, NaverNewsItem oldItem) {
6abe3ad 커밋에 어노테이션 추가했습니다~

2023-09-15 05:01 UTC, Queue-ri commented on dev/nusuy/ext-search-batch/.gitignore
> +application.properties
secret 정보를 제외한 yml 작성 내역은 커밋해주세요~
다른 사람들이 유선이의 서버를 빌드하려 할 때 필요합니다!

2023-09-15 05:04 UTC, nusuy commented on dev/nusuy/ext-search-batch/.gitignore
> +application.properties
8d65987 application.yml 파일 추가 후, gitignore에서 삭제했습니다!

2023-09-16 04:35 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/main/resources/application.yml
> +    secret: 3tsQ5Irie_
클라이언트 id와 secret은 별도 파일로 분리해서 gitignore 처리해주세요~

2023-09-16 04:57 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/resources/application.yml
> +    secret: 3tsQ5Irie_
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/7e49a94b03e24de1eb7d29207e2bd311c4a503b7 
Naver API Client secret 코드 application-secrets.yml 파일로 분리해 gitignore 처리했습니다.

2023-09-16 04:58 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/main/resources/application.yml
> +    secret: 3tsQ5Irie_
땡큐
클라 secret도 다시 발급받아줘~

2023-09-16 05:10 UTC, hyojeongchoi commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +        newsRepo.save(oldItem);
성능 측면에서 for 문 안에서  save 호출하는 것보다 for문으로 내용을 배열로 저장해서 적재하는 방식으로 고치는 방향이 더 좋을 것 같습니다!

2023-09-16 05:35 UTC, chaeeun-Han requested changes

2023-09-16 05:35 UTC, chaeeun-Han commented on dev/nusuy/ext-search-batch/.gitignore
> +application.yml
오픈소스로 공개될 목적의 경우 명세로 쓰일 파일들이기에, 환경변수 파일로 secret key를 분리하는게 좋을 것 같아요~

2023-09-16 05:35 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsItem.java
> +    @Column(nullable = false)//, length = 200)
naver 뉴스 api 응답에서 필수여부에 대한 언급이 없으므로 `nullable` 옵션은 빼는게 좋을 것 같아요~
id를 제외한 column들에서 빼주세요!

2023-09-16 05:35 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +    public void naverNewsApi ()  {
DB에 접근하는 메서드에는 `@Transactional` 어노테이션을 붙여주세요!

2023-09-16 05:35 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverResultVO.java
> +public class NaverResultVO {
`@Setter`에 의해 실질적으로 Dto 역할을 하고 있으므로, Dto로 수정해주세요~

2023-09-16 05:35 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NewsVO.java
사용하지 않는 파일로 보여 삭제하는 것이 좋을 것 같아요!

2023-09-17 02:52 UTC, nusuy commented on dev/nusuy/ext-search-batch/.gitignore
> +application.yml
8d65987 파일 추가 후, gitignore에서 삭제했습니다!

2023-09-17 07:43 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/service/RestTemplateService.java
> +    public String naverApiTest() throws CharacterCodingException {
b0be944 에 추가했습니다!

2023-09-17 07:43 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/service/RestTemplateService.java
> +                newsRepo.save(DBdata);
b0be944 에 수정했습니다!

2023-09-17 09:49 UTC, nusuy commented on dev/nusuy/ext-search-batch/src/main/java/com/cubix/extsearchbatch/service/DataUpdateService.java
> +        }
07efb11 예외 처리 수정했습니다~!

2023-09-18 06:05 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +                "https://openapi.naver.com/v1/search/news.json?query=%EC%A3%BC%EC%8B%9D&display=10&start=1&sort=sim",
166f031 수정했습니다~

2023-09-18 06:09 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverResultVO.java
> +public class NaverResultVO {
일반적으로 VO는 setter가 없는 것이 컨벤션이고, 로직 정황 상 네이버 API response를 deserialize하는데 사용하고 있으므로 DTO가 더 적합해보입니다.

2023-09-18 07:35 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +        System.out.println("뉴스 데이터 적재 완료");
3c73881 교체했슴다

2023-09-18 08:33 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/main/java/com/qriosity/extsearchbatch/NewsBatch.java
> +        newsRepo.save(oldItem);
3347c00 확인해주세요!

2023-09-18 08:46 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/domain/NaverNewsItem.java
> +    private Long id;
`@Id`로 이미 PK지정을 했기 때문에 `@Column`의 unique와 nullable 옵션은 제거하는게 가독성에 좋을 것 같습니다.

2023-09-18 08:58 UTC, nusuy approved these changes
다들 수고하셨습니다 🤩

2023-09-18 09:13 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/main/java/com/chaeeun/extsearchbatch/domain/NaverNewsItem.java
> +    private Long id;
0bee5be 에 제거했습니다~

2023-09-18 14:24 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsItem.java
> +    @Column(nullable = false)//, length = 200)
[e68fe5f87d2655b75ff166f01b116896d5f64f79](https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/e68fe5f87d2655b75ff166f01b116896d5f64f79) 이슈로 수정했습니다

2023-09-18 14:25 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsItem.java
> +    @Column(nullable = false)//, length = 200)
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/e68fe5f87d2655b75ff166f01b116896d5f64f79 로 수정했습니다

2023-09-18 14:48 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +    public void naverNewsApi ()  {
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/286c2d85dadca82e2be9671e555387afdc09c9d1 로 수정했습니다~

2023-09-18 14:48 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverResultVO.java
> +public class NaverResultVO {
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/3ef902ef31de4b8419ae3a487ec4ec6086c2287b 로 수정 완료했습니다

2023-09-18 14:49 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NewsVO.java
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/2d74a4a208f8aa006c07a9129b30218fe8bec14c ㅇㅣ슈로 수정 완료했습니다

2023-09-18 14:57 UTC, chaeeun-Han requested changes

2023-09-18 14:57 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +                    NaverNewsRepo.save(findNews);
성능 향상을 위해 save대신 리스트에 저장할 item들을 담아두고 saveAll로 for문 밖에서 한 번에 적재하는 것이 좋습니다

2023-09-18 14:59 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +    public void naverNewsApi ()  {
3ef902e 에 들어가야 할 수정사항이 286c2d8 에 들어가 있어서 롤백 단위 측면에서 사알짝 아쉬운디,, 시간이 늦었으니 다음 리뷰에선 신경써보도록 하고 지금은 패스합시다~

2023-09-18 15:05 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +    private String path;
환경변수거나 상수일 경우 대문자로 네이밍해주는게 가독성에 좋아보여요.

ex) baseUrl -> BASE_URL

그리고 수정할 겸 밑에 `@Transactional`이랑 한 줄 떨어지게 해주세요!

커밋 시맨틱은 `refactor`로 넣으심 될듯합니다😉

2023-09-18 16:03 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +    private String path;
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/8872c46f53025c0e50727380a13dc09c40f1316a 로 수정 완료했습니다!

2023-09-18 16:03 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/main/java/com/choihyojeong/extsearchbatch/NaverNewsService.java
> +                    NaverNewsRepo.save(findNews);
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/2/commits/a4f6249bf6b2d65f1ed27b7c6306984781827ca4 로 수정했습니다!

2023-09-18 22:48 UTC, chaeeun-Han approved these changes

2023-09-18 23:15 UTC, merged