Warm-up 실습 2주차 - Queue-ri
teamcors/EZPZ-Infra-Study pull request #4
Opened 2023-09-20 10:42 UTC by Queue-ri

- #3

2023-09-21 06:09 UTC, chaeeun-Han commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +    private final String KEYWORD = "주식";
키워드를 상수로 정한게 좋네요!👍

2023-09-21 06:23 UTC, chaeeun-Han requested changes

2023-09-21 06:23 UTC, chaeeun-Han commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +@Transactional
`@Transactional` 의 롤백 기능은 Test에서 아주 유용하지만, AUTO_INCREMENT(id값)는 롤백되지 않는 문제가 발생합니다.
dev db와 test db를 분리하지 않고 개발하고 있기에 이 부분을 개선해야할 것 같아요

2023-09-24 03:54 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +@Transactional
네 이에 대해서 채은님은 롤백하지 않는 방법을 사용하셨지만 그때 얘기 나눴듯이 사이드이펙트가 완전히 없으려면 테스트용 DB를 따로 두는 것이 맞는 것 같습니다. test profile 하나 더 두는 방식으로 수정해볼게요!

2023-09-25 11:28 UTC, hyojeongchoi commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +    private final String KEYWORD = "주식";
키워드를 상수로 빼두어서 진행한게 더 좋은 것 같습니다!

2023-09-26 02:43 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +    private final String KEYWORD = "주식";
땡큐합니다 키워드는 언제든지 바뀔 수 있으니까 빼놨어요

2023-09-26 11:40 UTC, Queue-ri commented on dev/queue-ri/ext-search-batch/src/test/java/com/qriosity/extsearchbatch/NewsBatchTest.java
> +@Transactional
f4f0079 로 반영했습니다~

2023-09-26 15:32 UTC, nusuy approved these changes

2023-09-26 15:33 UTC, chaeeun-Han approved these changes

2023-09-26 16:36 UTC, hyojeongchoi approved these changes

2023-09-26 16:38 UTC, merged