Warm-up 실습 2주차 - chaeeun-Han
teamcors/EZPZ-Infra-Study pull request #6
Opened 2023-09-20 11:04 UTC by chaeeun-Han

- #3

2023-09-20 11:17 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/.gitignore
커밋 메시지를 Exclude test secrets file 이라고 해도 될 것 같아~ 짧게 쓰는 것도 중요해서

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
`@RunWith` `@SpringBootTest` `@InjectMocks`의 사용 이유를 설명해주실 수 있나요?

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private String clientSecret;
저번에 효정이한테도 동일 코멘트 쓴 것 같은데 환경변수나 시크릿 등은 변수명을 대문자로 해서 컨벤션 지켜주면 좋을 것 같아요. (타 일반 변수와 구분하기 쉽도록 하기 위함)

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
`ReflectionTestUtils`를 사용한 이유가 있나요? 아마 특정 문제 때문일거라 생각합니다.
그렇다면 이 방법 말고 다른 대안은 없나요? 있다면 어떤게 있고, 각자의 장단점은 무엇인가요?

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    @Rollback(false)
롤백을 하지 않는 이유를 설명해주실 수 있나요?

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    public void 주식_단어가_포함되어있다() throws Exception {
코드 상에 한글을 사용한 네이밍은 지양했으면 좋겠습니다. 테스트명을 정해주고 싶은 거라면 `@DisplayName` 을 사용하면 됩니다.

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/resources/application.yml
> +    cache: false
타임리프 설정이 들어간 이유가 있나요?

2023-09-20 11:40 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
테스트 로직이 깔끔해서 보기 좋네요~

2023-09-20 11:50 UTC, Queue-ri requested changes
굿굿~ 리뷰거리 많아서 좋구만(?)

2023-09-20 12:20 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    @Rollback(false)
AUTO_INCREMENT로 지정했던 id 값은 롤백으로 되돌아가지 않기 때문에, 추후 데이터를 적재할 때 id 값이 밀리는 경우가 발생합니다. 현재로는 dev db와 test db가 동일하므로 롤백하지 않도록 했습니다

2023-09-20 12:22 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
test class에서는 clientId/clientSecret이 불러와지지만, newsBatchService에는 value가 넘어가지 않아서 `eflectionTestUtils`를 사용했습니다

2023-09-20 14:38 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
혹시 참고하신 레퍼런스가 있다면 링크해주실 수 있나요?

대안은 저도 찾아보겠습니다. 팀 전체적으로 알 필요가 있는 부분인 것 같아서!

2023-09-20 14:47 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    @Rollback(false)
네 오늘 시연에서 잘 확인했습니다. 테스트 DB는 일단 따로 분리해야 할 것 같고요,

적재 테스트는 현재 간단한 적재에 대해서만 테스트하는 것이 요구사항이었어서, 업데이트가 발생하는 등의 여러가지 파생 케이스는 별도의 테스트를 만들도록 차후의 task로 분리해야 할 것 같네요. (지금 수정하라는 것 x) 그리고 이것이 선행되면 그땐 롤백을 시키는 것이 나을 듯 합니다. 테스트가 CI랑 연결되면 경우에 따라 사소한 커밋마다 실행될 수도 있고 해서요.

2023-09-21 04:26 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private String clientSecret;
앗차차.. 0a05e2d 에 수정했습니다

2023-09-21 05:13 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    public void 주식_단어가_포함되어있다() throws Exception {
JUnit4 를 사용하고 있었기에 `@DisplayName`이 안 먹더라구요..
위의 코멘트에서 언급하셨던 `@RunWith`도 JUnit5에선 기본값이라길래 편의성을 위해 JUnit5로 업그레이드 했습니다!
50f449f c918ba7 에 수정해뒀습니다

2023-09-21 05:15 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/resources/application.yml
> +    cache: false
초기 스프링 설정할 때 참고했던 레퍼런스를 구석구석 살펴보지 못했었네요😥
찾아주셔서 감사합니다
a06a038 에 수정했습니다~

2023-09-21 05:27 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
https://roytuts.com/mock-an-autowired-value-field-in-spring-with-junit-mockito/
참고했던 레퍼런스입니다. 이 레퍼런스 이전에 Stack overflow를 봤었는데, 해당 레퍼런스는 못 찾겠네요..

+) 추가로 발견한 레퍼런스입니다.
https://stackoverflow.com/questions/52293575/value-annotation-not-working-in-junit-test

2023-09-21 05:40 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
`@SpringBootTest`
: Spring Boot 애플리케이션의 실제 의존성을 활성화하고 통합 테스트를 실행하기 위함입니다. 실제 DB에 접근해야하기 때문에 사용했습니다.

`@RunWith`

> Junit4 : `@RunWith(SpringRunner.class)`와 함께 사용
> Junit5 : 따로 명시할 필요 없음

: JUnit4를 사용하고 있었기에 해당 어노테이션을 사용했습니다. (c918ba7 JUnit4 -> JUnit5로 업그레이드 했습니다.)

`@InjectMocks`
: Mock 객체를 사용하면 실제 데이터베이스나 외부 서비스와의 통신을 피하므로 테스트를 더 빠르게 실행할 수 있기에 Mock 객체의 사용을 지향하려고 했습니다.
(그러나.. 실제 데이터베이스에 접근해야하므로 Repository class를 `@Mock`으로 선언하지 못하고 `@Autowired`로 객체를 주입하면서 Mock을 사용하고 있는 것 같진 않음..)
더 공부해보고 추가로 코멘트 달게요!

2023-09-24 04:03 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    public void 주식_단어가_포함되어있다() throws Exception {
아 그랬군요 JUnit5만 써봤어서 몰랐네요😮 다음에 디펜던시 버전 문제가 발생하면 업/다운그레이드하기 전에 한번 물어봐주세요~ 때로는 업그레이드가 답이 아닐수도 있어서

2023-09-24 04:06 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/resources/application.yml
> +    cache: false
a06a038 의 커밋 컨벤션은 refactor이 아니라 chore(conf) 인 것 같습니다.

2023-09-24 04:09 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    public void 주식_단어가_포함되어있다() throws Exception {
c918ba7 은 커밋 타입 chore(deps)로 조금 구체화해도 좋을 것 같아요. chore도 괜찮으니 일단 resolve하겠습니다.

2023-09-24 04:26 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
굿굿 일단 `@RunWith`는 이해가 되었고요,

`@SpringBootTest` 에 대해서는.. 좀 고민해봐야겠네요. 이게 실제 DB와 통신하면 통합 테스트, Mock으로 테스트하면 단위 테스트인 것 같은데 배치 자체가 단위로 테스트하기엔 모듈 나뉠 것이 별로 없고, 통합으로 하기엔 꼭 실제 DB와 통신시켜야 할 필요가 있나 싶어서요. 그런데 배치 내부적으로 외부 API(네이버)를 사용하기 때문에 이것까지 mocking하지 않는 이상 통합 테스트에 해당해서, 통합 테스트쪽으로 마음이 기울고 있긴 합니다.

- 외부 API mocking 참고: https://velog.io/@kyle/%EC%99%B8%EB%B6%80-API%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%ED%85%8C%EC%8A%A4%ED%8A%B8-%ED%95%A0-%EA%B2%83%EC%9D%B8%EA%B0%80

일단 우리에게 중요한건 전 배포과정을 겪고 관리하는 방법을 공부하는거니까, 이번주는 테스트 DB 분리 정도만 하고 제대로 된 테스트 환경 mocking은 차후의 refactoring task로 두는 것이 어떨까요?

2023-09-26 02:46 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
그게 저도 더 중요한 것 같아요 그렇게 수정해서 커밋하겠습니다!

2023-09-26 03:06 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/resources/application.yml
> +    cache: false
아 그렇군요!
4c3a8fc 에서 커밋 타입 수정하고 다시 올렸습니다

2023-09-26 04:23 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
테스트 DB 정보는 환경변수로 설정해둬서 따로 커밋이 들어가진 않았지만,
분리함에따라 롤백을 시행하도록 수정했습니다.

또한 구두로 리뷰해주셨을 때 키워드 테스트에서 '적재 한 것에 대해서만 키워드 존재 여부를 따져보는 것이 성능에 좋을 것 같다'는 점이 생각나 이 점 보완했습니다.
28bf377 0da5480

2023-09-26 12:18 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
효정이에게 남긴 코멘트와 동일하게, 28bf377 과 0da5480 의 커밋 메시지가 포괄적인 것 같습니다. 그 이유는 쉽게 생각해서 차후 keyword/save test에 또 업데이트를 해야할 상황을 가정해보면 됩니다. 지금 작성한 이 커밋 메시지가 그때의 메시지와 명확하게 구분될 수 있을까요?

제가 요청드린 부분이
1. 롤백을 살리자
2. 새로 적재한 부분만 검사하자

이 둘이었으니, 이를 기준으로 커밋을 나눠보면 어떨까요?

2023-09-26 13:21 UTC, Queue-ri commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
잘 읽었습니다. 제가 찾은 레퍼런스도 드릴게요. 
https://kkambi.tistory.com/210

결론적으로 `ReflectionTestUtils`가 광범위하게 사용되기에는 부적절하나, 적어도 유닛 테스트에선 적절한 방법인 것 같습니다.

다만 이건 제가 예전에 읽었던 레퍼이고 이게 나름 리플렉션의 대안이 되지 않을까 했었는데요,
https://jaehoney.tistory.com/218
여기서 말하는 프로덕션 클래스를 우리의 배치 클래스로 이해했습니다만, 저의 경우엔 `@EnableConfigurationProperties`도 안되고 `@SpringBootTest`도 안되더라고요..?

(의심가는 다른 부분이 있긴 한데, 확인해보고 맞으면 스터디 할 겸 공유드릴게요.)

`ReflectionTestUtils` 말고 그 외의 다른 방법으로는 DI 중 생성자 주입이 가능할 것 같은데, 이건 뭔가 음... 제 맘에 들지 않아서 더 찾아봐야 할 것 같아요.

이 토픽에 대해선 따로 이슈를 남기는게 좋을 것 같아서 하나 작성하겠습니다~

2023-09-26 15:23 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    private NewsBatchService newsBatchService;
아..! 추후에 구분하기 힘들겠네요.
"말씀해주신 부분 + 로그 추가"로 총 3개의 커밋으로 세분화 했습니다
4db42c1 0adc9d3 cc7797e

2023-09-26 15:39 UTC, chaeeun-Han commented on dev/chaeeun-han/ext-search-batch/src/test/java/com/chaeeun/extsearchbatch/service/NewsBatchServiceTest.java
> +    }
공유해주셔서 감사합니다!! 해당 부분에 대해서는 깊게 알아야 할 필요가 있어보이네요😂

2023-09-26 16:21 UTC, Queue-ri approved these changes

2023-09-26 16:37 UTC, hyojeongchoi approved these changes

2023-09-26 16:50 UTC, nusuy approved these changes

2023-09-27 05:11 UTC, merged