Warm-up 실습 2주차 - hyojeongchoi #7
teamcors/EZPZ-Infra-Study pull request #7
Opened 2023-09-20 11:17 UTC by hyojeongchoi

- #3

2023-09-21 04:11 UTC, chaeeun-Han requested changes

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +    private WebApplicationContext context;
사용하지 않는 것으로 보여 삭제하는게 좋을 것 같아요~

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
추후 유지보수의 편의성을 위해 미리 만들어둔 Batch코드를 사용해서 Test 코드를 짜는 것이 좋을 것 같아요!

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
> +    private WebApplicationContext context;
NaverNewsBatchTest와 같이 불필요한 코드는 삭제해주세요~

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +                System.out.println("뉴스 데이터 적재 완료");
`System.out.println`을 `@Slf4j`를 최상단에 추가한 후 `log.info`로 대체합시다!
테스트 환경에서는 `@Slf4j`만 쓴다고 바로 사용할 수 없으므로 `build.gradle` 파일에서 아래의 의존성을 넣는 걸 참고해주세요.
97번째 줄 외의 다른 부분에서 `System.out.println` 쓴 것들도 참고해주세요!
```
testCompileOnly 'org.projectlombok:lombok'
testAnnotationProcessor 'org.projectlombok:lombok' 
```

로그를 많이 남겨서 과정을 상세하게 보여주는 것 너무 좋네요👍

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +@AutoConfigureMockMvc
모킹을 사용하지 않는다면 `@AutoConfigureMockMvc` 애너테이션도 필요하지 않는 걸로 보이는데, 혹시 다른 이유로 사용한 걸까요?

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
Batch Service에 대하여
1. 10개의 뉴스 데이터가 잘 적재되는지
2. 키워드를 내포하고 있는지

로 세분화하여 확인하는 테스트 이므로 하나의 Test파일에 Batch test와 keyword test를 만드는 걸 추천합니다

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +        Assertions.assertThat(newNewsLen).isEqualTo(saveNewsLen);
《JUnit in Action》에서는 "assert 메서드를 호출할 때는 에러 메시지도 무조건 함께 기입하는 습관"을 들이라고 권하고 있습니다.
따라서 테스트가 실패했을 경우 assert뒤에 `as()`를 사용해 실패 원인을 작성하는 것을 추천합니다.

EX) `Assertions.assertThat(newNewsLen).as("newNewsLen과 saveNewsLen이 같지 않음").isEqualTo(saveNewsLen);`

2023-09-21 04:11 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
> +    @Test
컨벤션은 아니지만 일반적으로 `@Test` 후에 `@DisplayName`을 작성하고, 이로써 테스트 메서드가 무엇을 테스트하는지 명확하게 드러날 수 있을 것 같아 위치를 바꾸는게 좋을 것 같아요!

2023-09-21 06:43 UTC, chaeeun-Han requested changes

2023-09-21 06:43 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +    private String PATH;
이전에 규리언니가 리뷰했었던 것 같은데,
naver 뉴스 API 에 대한 url은 이미 네이버 개발자 센터의 예시에서 공개적으로 노출되어있기 때문에 시크릿 정보로 담지 않아도 될 것 같아요!

2023-09-24 03:41 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +    private String PATH;
네 어차피 공개된 내용이고 키 없으면 접근 거부되는 엔트리라 id랑 key만 잘 관리하면 될 것 같습니다. 나중에 환경변수 많아지면 관리하기도 힘들어져요 ^^...

2023-09-24 03:45 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +                System.out.println("뉴스 데이터 적재 완료");
네 저도 리뷰시간에 말씀드렸지만 CI에 연결되면 CI 로그로 테스트 결과를 확인할 때가 많은데 그런점에서 테스트 과정 확인이 용이하도록 작성하신 점이 매우 좋았습니다.

2023-09-26 02:45 UTC, Queue-ri commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +        Assertions.assertThat(newNewsLen).isEqualTo(saveNewsLen);
`as`는 저도 배워갑니다~

2023-09-26 03:59 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/452c4ac7ce91442086ccf65f9d2d2d08fd5cd608 확인해주세요!

2023-09-26 04:00 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/b81535a8a898a3b87580c947c962783ff7aae438 확인해주세요~

2023-09-26 04:00 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +    private WebApplicationContext context;
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/7e66aeb1856b6743e35ce99b57c6c0d44a881c7a 으로 수정했습니다

2023-09-26 04:00 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
> +    private WebApplicationContext context;
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/7e66aeb1856b6743e35ce99b57c6c0d44a881c7a 으로 수정했습니다

2023-09-26 04:01 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +@AutoConfigureMockMvc
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/7e66aeb1856b6743e35ce99b57c6c0d44a881c7a 으로 수정했습니다

2023-09-26 04:01 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +    private String PATH;
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/cb7553232c9039998fe81e25c27051d9fd6bf1ee 로 수정했어요~!

2023-09-26 04:01 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsKeywordTest.java
> +    @Test
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/dc8d0db42336478c59856f40727093b39893c077 로 수정했습니다

2023-09-26 04:02 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +        Assertions.assertThat(newNewsLen).isEqualTo(saveNewsLen);
좋은 방법인거 같아요!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/df87224505a27b4f856f2f51ac306b3b85e29cf8 로 수정해뒀습니다

2023-09-26 04:02 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
> +                System.out.println("뉴스 데이터 적재 완료");
감사합니다!!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/2027f1656fba92a01c68ae9619e97262e9cac490 로 수정해서 올려뒀습니다!

2023-09-26 04:39 UTC, chaeeun-Han commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
Batch 코드 사용해서 test를 재구성한 거 확인했습니다!

그런데 httpConnect(), restTemplate 및 import 등
Batch 코드를 사용하기 이전에 정의했던 변수들을 확인하고 불필요한 것들을 제거하는 작업이 필요해보여요!

2023-09-26 05:43 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/commit/804c93abcc481cfdda88491d682bdf4f3afdb043 확인해서 다시 수정했습니다!! 
불필요한 import문 제거 및 사용되지 않은 httpConnect() 등의 함수 제거했습니다

2023-09-26 11:41 UTC, Queue-ri approved these changes

2023-09-26 11:59 UTC, Queue-ri requested changes
코드 제거 관련 커밋은 refactor인 것 같습니다.
제가 읽은 레퍼 같이 드릴게요. https://stackoverflow.com/questions/48075169/semantic-commit-type-when-remove-something

2023-09-26 15:03 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
@Queue-ri 리뷰 댓글이 안달려 여기에 남깁니다!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/commit/0d0b567418409c3d4dfa1b66a11915c1250db667 리뷰로 commit 오타 수정했습니다.

https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/commit/d877f925aac53be3794216bc2cb7b7270884923f 로 refactor로 수정하고 body로 더 자세한 수정사항 기록해두었습니다

2023-09-26 15:14 UTC, hyojeongchoi reviewed
@Queue-ri 
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/20cd2f3f8acdc6de0a95d273bc60c4a1942040d5 리뷰로 commit 오타 수정했습니다.

https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/aa0f75a40e517e9c53aa67abdcffb0b1fa77b7cd  refactor로 수정하고 body로 더 자세한 수정사항 기록해두었습니다

2023-09-26 15:15 UTC, hyojeongchoi commented on dev/choihyojeong/ext-search-batch/src/test/java/com/choihyojeong/extsearchbatch/NaverNewsBatchTest.java
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/commit/d877f925aac53be3794216bc2cb7b7270884923f 로 커밋메시지 수정했습니다~!

2023-09-26 15:25 UTC, Queue-ri commented
@hyojeongchoi 네 감사합니다.
개인적으로는 아직 refactor라고 생각되는 chore 커밋들이 있지만 이쯤 넘어가도 좋을 것 같아요.

근데 df87224 는 로그 추가의 의미가 있어서 저라면 feat으로 작성했을 것 같은데.. 이거까지 수정 가능하실까요?
그냥 interactive rebase에서 `git commit --amend -m "~~"` 해서 수정할 수 있어서 엄청 번거롭진 않은데

2023-09-26 15:29 UTC, chaeeun-Han approved these changes

2023-09-26 15:38 UTC, hyojeongchoi reviewed
@Queue-ri 
네 감사합니다!
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/187c9f3abc31ce7cb1537acf7e667b7a8faec95a  feat으로 수정해두었습니다!

2023-09-26 16:26 UTC, Queue-ri commented
@hyojeongchoi 효정쓰... 미안한데 내가 feat이라고 했을때 뭔가 이상하다는 생각 안들었어?....
### test 잖아😂🤣.......🙄
미안합니다...^^.... ~~_이래서 리뷰 코멘트도 무조건 신뢰하면 안돼...!_~~

2023-09-26 16:34 UTC, hyojeongchoi reviewed
@Queue-ri 
앗!... 순간 헷갈렸어 ㅋㅋㅋㅋㅋ
https://github.com/GDSC-CUBIX/EZPZ-Infra-Study/pull/7/commits/db27a12aa229a328c58611894d2e9c682fd9ed4a 수정했습니당~!~!

2023-09-26 16:37 UTC, Queue-ri approved these changes

2023-09-26 16:38 UTC, Queue-ri commented
수고했습니다~

2023-09-26 16:49 UTC, nusuy approved these changes

2023-09-26 16:55 UTC, merged